allowBuilds:
  "@tailwindcss/oxide@4.1.18": true
  esbuild@0.25.12 || 0.27.2: true

engineStrict: true

overrides:
  drizzle-orm>@types/mssql: "-"
  drizzle-orm>mssql: "-"
  drizzle-kit>esbuild: 0.27.2

strictDepBuilds: true
